### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by ViralBShah** [JuliaCN/juliacn.github.io#5]
I think it is best to link to the English version of the blog. Blogs that have chinese translations now have Chinese titles in the Julia blog.

**Comment by findmyway** [comment]
Sounds reasonable.

**Comment by findmyway** [comment]
Done.

It seems the English version of blog has some problem.
The titles in the first row are empty.

![image](https://user-images.githubusercontent.com/5612003/52188944-88517a00-2870-11e9-9620-ff57b56230a7.png)

**Comment by ViralBShah** [comment]
I don't know what's causing that.

**Comment by ViralBShah** [comment]
Filed: https://github.com/JuliaLang/www.julialang.org/issues/301
