### ISSUE TITLE
现在的logo不是很有区分度？

### ISSUE THREAD

**Issue by Roger-luo** [JuliaCN/juliacn.github.io#6]
我正在写JuliaCon的slide，我发现现在org的logo感觉不是很有区分度，如果亮度不够基本上看起来就是Julia的三个球。我们是不是考虑换一个区别明显的logo？

**Comment by Gnimuc** [comment]
现在这个是我随便画的，最好换个。

**Comment by Roger-luo** [comment]
![图像 5](https://user-images.githubusercontent.com/8445510/61190718-b5e7ee00-a66e-11e9-950f-e5d3b5ee503b.png)
我画了一个大家觉得怎么样？

Update：因为时间有点紧，我先把现在的logo换了
