### ISSUE TITLE
更新下首页？

### ISSUE THREAD

**Issue by findmyway** [JuliaCN/juliacn.github.io#8]
我看英文的首页更新了，我们也同步下？

**Comment by Roger-luo** [comment]
如果有人有空的话可以先开一个PR？我们可以有时间的话一起改。

目前首页换了Franklin.jl然后Franklin正在支持i18n：https://github.com/JuliaLang/www.julialang.org/issues/292#issuecomment-636176247 

现在update的话我们可能得先把新的基于Franklin的网站给搬运过来。

**Comment by findmyway** [comment]
我下周周末可以做一下这个，最近试了下Franklin.jl，大概比较熟悉了

**Comment by Roger-luo** [comment]
现在应该已经差不多了。
